name: whiskers
description: A templating library that implements the Mustache template specification, but is extendable.
version: 0.1.1
homepage: https://github.com/serverpod/whiskers
repository: https://github.com/serverpod/whiskers
issue_tracker: https://github.com/serverpod/whiskers/issues

topics:
  - mustache
  - template
  - templating
  - html
  - parser

environment:
  sdk: ^3.8.0

dev_dependencies:
  test: ^1.25.5
